import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

/**
 * Shared genuine-foreign corpus for measured-runtime import evidence.
 *
 * Every fixture is a committed static artifact under
 * `conformance-fixtures/import-foreign/<id>/<relPath>` authored in the foreign
 * tool's canonical on-disk form — it is NEVER produced by the tool's own forward
 * pipeline. Using these committed files (rather than forward-render → import) as
 * the oracle makes the resulting artifacts *independent* measured evidence: they
 * exercise the real, end-to-end `importRun` against genuinely-foreign inputs and
 * catch serializer drift a self-referential oracle cannot.
 */

export interface ForeignFixture {
  /** Registry target id the fixture belongs to. */
  id: string;
  /** Canonical on-disk path of the foreign file, relative to a project root. */
  relPath: string;
}

/** One genuinely-foreign fixture per fully-invertible import-stable target. */
export const FOREIGN_FIXTURES: ReadonlyArray<ForeignFixture> = [
  { id: 'claude-code', relPath: '.claude/team-guardrails.md' },
  { id: 'cursor', relPath: '.cursor/rules/review-checklist.mdc' },
  { id: 'windsurf', relPath: '.windsurf/rules/style-rules.md' },
  { id: 'cline', relPath: '.clinerules/safety-rules.md' },
  { id: 'roo-code', relPath: '.roo/rules/commit-rules.md' },
  { id: 'codex-cli', relPath: '.codex/prompts/summarize.toml' },
  { id: 'gemini-cli', relPath: '.gemini/commands/explain.toml' },
  { id: 'goose', relPath: '.goose/recipes/refactor.yaml' },
  { id: 'github-copilot', relPath: '.github/instructions/test-guidance.instructions.md' },
];

export const FIXTURE_ROOT = path.join(process.cwd(), 'conformance-fixtures', 'import-foreign');
export const RESULTS_DIR = path.join(process.cwd(), 'test-results');

/** Create a real temp directory (realpath-resolved so containment checks are stable). */
export function makeTempDir(prefix: string): string {
  return fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), prefix)));
}

/** Read the committed genuine-foreign content for a fixture (the independent oracle). */
export function readForeignContent(fixture: ForeignFixture): string {
  return fs.readFileSync(path.join(FIXTURE_ROOT, fixture.id, fixture.relPath), 'utf8');
}

/**
 * Stage a fixture's committed foreign content into `dir` at its canonical path.
 * Returns the absolute path written. The content is the on-disk oracle, never
 * regenerated by the pipeline.
 */
export function stageForeign(dir: string, fixture: ForeignFixture): string {
  const abs = path.join(dir, fixture.relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, readForeignContent(fixture));
  return abs;
}

/** Write a measured-runtime evidence artifact to `test-results/<name>`. */
export function writeArtifact(name: string, payload: Record<string, unknown>): void {
  fs.mkdirSync(RESULTS_DIR, { recursive: true });
  fs.writeFileSync(path.join(RESULTS_DIR, name), JSON.stringify(payload, null, 2));
}
